import type {
    User,
    Client,
    Project,
    Task,
    TimeEntry,
    Invoice,
    CommunicationLog,
    FileItem,
    Activity,
    Notification,
} from '@/types'

// Mock Users
export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Rahul Sharma',
        email: 'rahul@nexprism.com',
        role: 'owner',
        phone: '+91 98765 43210',
    },
    {
        id: 'u2',
        name: 'Priya Singh',
        email: 'priya@nexprism.com',
        role: 'pm',
        phone: '+91 98765 43211',
    },
    {
        id: 'u3',
        name: 'Amit Kumar',
        email: 'amit@nexprism.com',
        role: 'developer',
        phone: '+91 98765 43212',
    },
    {
        id: 'u4',
        name: 'Sneha Patel',
        email: 'sneha@nexprism.com',
        role: 'developer',
        phone: '+91 98765 43213',
    },
    {
        id: 'u5',
        name: 'Vikram Desai',
        email: 'vikram@nexprism.com',
        role: 'developer',
        phone: '+91 98765 43214',
    },
    {
        id: 'u6',
        name: 'Anjali Verma',
        email: 'anjali@nexprism.com',
        role: 'developer',
        phone: '+91 98765 43215',
    },
]

// Mock Clients
export const mockClients: Client[] = [
    {
        id: 'c1',
        name: 'Rajesh Gupta',
        company: 'TechStart Solutions',
        email: 'rajesh@techstart.com',
        phone: '+91 99887 76655',
        address: 'Mumbai, Maharashtra',
        type: 'retainer',
        status: 'active',
        notes: 'Long-term client, monthly retainer',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2026-01-10'),
    },
    {
        id: 'c2',
        name: 'Meera Kapoor',
        company: 'Fashion Hub India',
        email: 'meera@fashionhub.in',
        phone: '+91 99887 76656',
        address: 'Delhi, India',
        type: 'one-time',
        status: 'active',
        notes: 'E-commerce project',
        createdAt: new Date('2024-03-20'),
        updatedAt: new Date('2026-01-12'),
    },
    {
        id: 'c3',
        name: 'Suresh Reddy',
        company: 'EduLearn Platform',
        email: 'suresh@edulearn.com',
        phone: '+91 99887 76657',
        address: 'Bangalore, Karnataka',
        type: 'retainer',
        status: 'active',
        notes: 'Education platform, ongoing development',
        createdAt: new Date('2024-05-10'),
        updatedAt: new Date('2026-01-14'),
    },
    {
        id: 'c4',
        name: 'Kavita Joshi',
        company: 'HealthCare Plus',
        email: 'kavita@healthcareplus.in',
        phone: '+91 99887 76658',
        address: 'Pune, Maharashtra',
        type: 'one-time',
        status: 'active',
        createdAt: new Date('2024-07-05'),
        updatedAt: new Date('2026-01-11'),
    },
    {
        id: 'c5',
        name: 'Arjun Mehta',
        company: 'Real Estate Pro',
        email: 'arjun@realestatepro.com',
        phone: '+91 99887 76659',
        address: 'Ahmedabad, Gujarat',
        type: 'one-time',
        status: 'active',
        createdAt: new Date('2024-08-12'),
        updatedAt: new Date('2026-01-13'),
    },
    {
        id: 'c6',
        name: 'Deepa Nair',
        company: 'Food Delivery Co',
        email: 'deepa@fooddelivery.in',
        phone: '+91 99887 76660',
        address: 'Kochi, Kerala',
        type: 'retainer',
        status: 'active',
        createdAt: new Date('2024-09-18'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 'c7',
        name: 'Manish Agarwal',
        company: 'Finance Guru',
        email: 'manish@financeguru.com',
        phone: '+91 99887 76661',
        address: 'Jaipur, Rajasthan',
        type: 'one-time',
        status: 'active',
        createdAt: new Date('2024-10-22'),
        updatedAt: new Date('2026-01-09'),
    },
    {
        id: 'c8',
        name: 'Pooja Iyer',
        company: 'Travel Buddy',
        email: 'pooja@travelbuddy.in',
        phone: '+91 99887 76662',
        address: 'Chennai, Tamil Nadu',
        type: 'one-time',
        status: 'active',
        createdAt: new Date('2024-11-05'),
        updatedAt: new Date('2026-01-08'),
    },
    {
        id: 'c9',
        name: 'Rohit Saxena',
        company: 'Auto Parts Hub',
        email: 'rohit@autoparts.com',
        phone: '+91 99887 76663',
        address: 'Lucknow, UP',
        type: 'retainer',
        status: 'active',
        createdAt: new Date('2024-12-01'),
        updatedAt: new Date('2026-01-07'),
    },
    {
        id: 'c10',
        name: 'Shalini Rao',
        company: 'Beauty Salon Chain',
        email: 'shalini@beautysalon.in',
        phone: '+91 99887 76664',
        address: 'Hyderabad, Telangana',
        type: 'one-time',
        status: 'inactive',
        createdAt: new Date('2023-11-15'),
        updatedAt: new Date('2025-12-20'),
    },
]

// Mock Projects
export const mockProjects: Project[] = [
    {
        id: 'p1',
        name: 'TechStart Corporate Website',
        clientId: 'c1',
        type: 'website',
        status: 'completed',
        startDate: new Date('2024-02-01'),
        deadline: new Date('2024-04-30'),
        dueDate: new Date('2024-04-30'),
        budget: 250000,
        paymentModel: 'milestone',
        description: 'Modern corporate website with CMS',
        milestones: [
            { id: 'm1', name: 'Design', dueDate: new Date('2024-02-28'), amount: 75000, percentage: 30, completed: true, completedAt: new Date('2024-02-27') },
            { id: 'm2', name: 'Development', dueDate: new Date('2024-04-15'), amount: 125000, percentage: 50, completed: true, completedAt: new Date('2024-04-12') },
            { id: 'm3', name: 'Launch', dueDate: new Date('2024-04-30'), amount: 50000, percentage: 20, completed: true, completedAt: new Date('2024-04-28') },
        ],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-04-30'),
    },
    {
        id: 'p2',
        name: 'Fashion Hub E-commerce Platform',
        clientId: 'c2',
        type: 'ecommerce',
        status: 'in-progress',
        startDate: new Date('2024-04-01'),
        deadline: new Date('2026-03-31'),
        dueDate: new Date('2026-03-31'),
        budget: 850000,
        paymentModel: 'milestone',
        description: 'Full-featured e-commerce platform with payment gateway',
        milestones: [
            { id: 'm4', name: 'Phase 1 - Core', dueDate: new Date('2024-06-30'), amount: 300000, percentage: 35, completed: true, completedAt: new Date('2024-06-28') },
            { id: 'm5', name: 'Phase 2 - Features', dueDate: new Date('2024-10-31'), amount: 350000, percentage: 41, completed: true, completedAt: new Date('2024-10-29') },
            { id: 'm6', name: 'Phase 3 - Launch', dueDate: new Date('2026-03-31'), amount: 200000, percentage: 24, completed: false },
        ],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-03-25'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 'p3',
        name: 'EduLearn Mobile App',
        clientId: 'c3',
        type: 'web-app',
        status: 'in-progress',
        startDate: new Date('2024-06-01'),
        deadline: new Date('2026-02-28'),
        dueDate: new Date('2026-02-28'),
        budget: 1200000,
        paymentModel: 'retainer',
        description: 'Progressive web app for online learning',
        milestones: [],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-05-15'),
        updatedAt: new Date('2026-01-14'),
    },
    {
        id: 'p4',
        name: 'HealthCare Plus Portal',
        clientId: 'c4',
        type: 'web-app',
        status: 'review',
        startDate: new Date('2024-08-01'),
        deadline: new Date('2026-01-31'),
        dueDate: new Date('2026-01-31'),
        budget: 450000,
        paymentModel: 'advance',
        description: 'Patient management portal',
        milestones: [],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-07-10'),
        updatedAt: new Date('2026-01-12'),
    },
    {
        id: 'p5',
        name: 'Real Estate Pro Website',
        clientId: 'c5',
        type: 'website',
        status: 'in-progress',
        startDate: new Date('2024-09-01'),
        deadline: new Date('2026-02-15'),
        dueDate: new Date('2026-02-15'),
        budget: 320000,
        paymentModel: 'milestone',
        description: 'Property listing website with search',
        milestones: [
            { id: 'm7', name: 'Design & Prototype', dueDate: new Date('2024-10-15'), amount: 96000, percentage: 30, completed: true, completedAt: new Date('2024-10-14') },
            { id: 'm8', name: 'Development', dueDate: new Date('2026-01-31'), amount: 160000, percentage: 50, completed: false },
            { id: 'm9', name: 'Testing & Launch', dueDate: new Date('2026-02-15'), amount: 64000, percentage: 20, completed: false },
        ],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-08-20'),
        updatedAt: new Date('2026-01-13'),
    },
    {
        id: 'p6',
        name: 'Food Delivery App',
        clientId: 'c6',
        type: 'web-app',
        status: 'in-progress',
        startDate: new Date('2024-10-01'),
        deadline: new Date('2026-04-30'),
        dueDate: new Date('2026-04-30'),
        budget: 950000,
        paymentModel: 'retainer',
        description: 'Food ordering and delivery platform',
        milestones: [],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-09-20'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 'p7',
        name: 'Finance Guru Landing Page',
        clientId: 'c7',
        type: 'landing',
        status: 'in-progress',
        startDate: new Date('2024-11-01'),
        deadline: new Date('2026-01-25'),
        dueDate: new Date('2026-01-25'),
        budget: 75000,
        paymentModel: 'advance',
        description: 'High-converting landing page',
        milestones: [],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-10-25'),
        updatedAt: new Date('2026-01-10'),
    },
    {
        id: 'p8',
        name: 'Travel Buddy Platform',
        clientId: 'c8',
        type: 'web-app',
        status: 'planning',
        startDate: new Date('2024-12-01'),
        deadline: new Date('2026-05-31'),
        dueDate: new Date('2026-05-31'),
        budget: 680000,
        paymentModel: 'milestone',
        description: 'Travel booking and itinerary platform',
        milestones: [
            { id: 'm10', name: 'Planning & Design', dueDate: new Date('2026-01-31'), amount: 204000, percentage: 30, completed: false },
            { id: 'm11', name: 'Development', dueDate: new Date('2026-04-30'), amount: 340000, percentage: 50, completed: false },
            { id: 'm12', name: 'Launch', dueDate: new Date('2026-05-31'), amount: 136000, percentage: 20, completed: false },
        ],
        pmId: 'u2',
        members: [],
        createdAt: new Date('2024-11-10'),
        updatedAt: new Date('2026-01-08'),
    },
]

// Mock Tasks (100 tasks across projects)
export const mockTasks: Task[] = [
    // Project p2 - Fashion Hub E-commerce
    {
        id: 't1',
        title: 'Design product listing page',
        description: 'Create responsive product grid with filters',
        projectId: 'p2',
        status: 'done',
        priority: 'high',
        assigneeId: 'u3',
        dueDate: new Date('2026-01-10'),
        estimatedHours: 16,
        labels: ['design', 'frontend'],
        checklist: [
            { id: 'ch1', text: 'Wireframe', completed: true },
            { id: 'ch2', text: 'UI Design', completed: true },
            { id: 'ch3', text: 'Responsive', completed: true },
        ],
        createdAt: new Date('2026-01-05'),
        updatedAt: new Date('2026-01-11'),
    },
    {
        id: 't2',
        title: 'Implement shopping cart',
        description: 'Add to cart, update quantity, remove items',
        projectId: 'p2',
        status: 'in-progress',
        priority: 'urgent',
        assigneeId: 'u4',
        dueDate: new Date('2026-01-18'),
        estimatedHours: 20,
        labels: ['frontend', 'backend'],
        checklist: [
            { id: 'ch4', text: 'Cart state management', completed: true },
            { id: 'ch5', text: 'Add/Remove items', completed: true },
            { id: 'ch6', text: 'Persist cart', completed: false },
        ],
        createdAt: new Date('2026-01-08'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 't3',
        title: 'Payment gateway integration',
        description: 'Integrate Razorpay for payments',
        projectId: 'p2',
        status: 'review',
        priority: 'urgent',
        assigneeId: 'u5',
        dueDate: new Date('2026-01-20'),
        estimatedHours: 24,
        labels: ['backend', 'payment'],
        checklist: [
            { id: 'ch7', text: 'Setup Razorpay', completed: true },
            { id: 'ch8', text: 'Test payments', completed: true },
            { id: 'ch9', text: 'Handle webhooks', completed: false },
        ],
        createdAt: new Date('2026-01-10'),
        updatedAt: new Date('2026-01-16'),
    },
    {
        id: 't4',
        title: 'Order management dashboard',
        description: 'Admin panel for managing orders',
        projectId: 'p2',
        status: 'todo',
        priority: 'medium',
        assigneeId: 'u3',
        dueDate: new Date('2026-01-25'),
        estimatedHours: 18,
        labels: ['admin', 'frontend'],
        checklist: [],
        createdAt: new Date('2026-01-12'),
        updatedAt: new Date('2026-01-12'),
    },
    {
        id: 't5',
        title: 'Product search & filters',
        description: 'Implement advanced search with filters',
        projectId: 'p2',
        status: 'client-approval',
        priority: 'high',
        assigneeId: 'u4',
        dueDate: new Date('2026-01-22'),
        estimatedHours: 16,
        labels: ['frontend', 'backend'],
        checklist: [
            { id: 'ch10', text: 'Search API', completed: true },
            { id: 'ch11', text: 'Filter UI', completed: true },
        ],
        createdAt: new Date('2026-01-09'),
        updatedAt: new Date('2026-01-14'),
    },
    // Project p3 - EduLearn
    {
        id: 't6',
        title: 'Video player component',
        description: 'Custom video player with controls',
        projectId: 'p3',
        status: 'in-progress',
        priority: 'high',
        assigneeId: 'u5',
        dueDate: new Date('2026-01-19'),
        estimatedHours: 20,
        labels: ['frontend', 'video'],
        checklist: [
            { id: 'ch12', text: 'Basic player', completed: true },
            { id: 'ch13', text: 'Custom controls', completed: false },
            { id: 'ch14', text: 'Progress tracking', completed: false },
        ],
        createdAt: new Date('2026-01-11'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 't7',
        title: 'Quiz module',
        description: 'Interactive quiz with timer and scoring',
        projectId: 'p3',
        status: 'todo',
        priority: 'medium',
        assigneeId: 'u6',
        dueDate: new Date('2026-01-28'),
        estimatedHours: 24,
        labels: ['frontend', 'backend'],
        checklist: [],
        createdAt: new Date('2026-01-13'),
        updatedAt: new Date('2026-01-13'),
    },
    {
        id: 't8',
        title: 'Student dashboard',
        description: 'Dashboard showing enrolled courses and progress',
        projectId: 'p3',
        status: 'in-progress',
        priority: 'high',
        assigneeId: 'u3',
        dueDate: new Date('2026-01-21'),
        estimatedHours: 18,
        labels: ['frontend'],
        checklist: [
            { id: 'ch15', text: 'Course list', completed: true },
            { id: 'ch16', text: 'Progress charts', completed: false },
        ],
        createdAt: new Date('2026-01-10'),
        updatedAt: new Date('2026-01-15'),
    },
    // Project p5 - Real Estate
    {
        id: 't9',
        title: 'Property listing cards',
        description: 'Design and implement property cards',
        projectId: 'p5',
        status: 'done',
        priority: 'high',
        assigneeId: 'u4',
        dueDate: new Date('2026-01-12'),
        estimatedHours: 12,
        labels: ['frontend', 'design'],
        checklist: [
            { id: 'ch17', text: 'Card design', completed: true },
            { id: 'ch18', text: 'Responsive', completed: true },
        ],
        createdAt: new Date('2026-01-06'),
        updatedAt: new Date('2026-01-13'),
    },
    {
        id: 't10',
        title: 'Advanced search filters',
        description: 'Location, price, type filters',
        projectId: 'p5',
        status: 'in-progress',
        priority: 'urgent',
        assigneeId: 'u5',
        dueDate: new Date('2026-01-17'),
        estimatedHours: 16,
        labels: ['frontend', 'backend'],
        checklist: [
            { id: 'ch19', text: 'Filter UI', completed: true },
            { id: 'ch20', text: 'API integration', completed: false },
        ],
        createdAt: new Date('2026-01-08'),
        updatedAt: new Date('2026-01-15'),
    },
    // Project p6 - Food Delivery
    {
        id: 't11',
        title: 'Restaurant listing page',
        description: 'Display restaurants with ratings',
        projectId: 'p6',
        status: 'review',
        priority: 'high',
        assigneeId: 'u3',
        dueDate: new Date('2026-01-16'),
        estimatedHours: 14,
        labels: ['frontend'],
        checklist: [
            { id: 'ch21', text: 'List view', completed: true },
            { id: 'ch22', text: 'Ratings display', completed: true },
        ],
        createdAt: new Date('2026-01-09'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 't12',
        title: 'Real-time order tracking',
        description: 'Track order status in real-time',
        projectId: 'p6',
        status: 'todo',
        priority: 'medium',
        assigneeId: 'u6',
        dueDate: new Date('2026-01-24'),
        estimatedHours: 22,
        labels: ['backend', 'realtime'],
        checklist: [],
        createdAt: new Date('2026-01-12'),
        updatedAt: new Date('2026-01-12'),
    },
    // Project p7 - Finance Guru Landing
    {
        id: 't13',
        title: 'Hero section design',
        description: 'Eye-catching hero with CTA',
        projectId: 'p7',
        status: 'done',
        priority: 'high',
        assigneeId: 'u4',
        dueDate: new Date('2026-01-14'),
        estimatedHours: 8,
        labels: ['design', 'frontend'],
        checklist: [
            { id: 'ch23', text: 'Design mockup', completed: true },
            { id: 'ch24', text: 'Implementation', completed: true },
        ],
        createdAt: new Date('2026-01-10'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 't14',
        title: 'Contact form integration',
        description: 'Lead capture form with validation',
        projectId: 'p7',
        status: 'in-progress',
        priority: 'medium',
        assigneeId: 'u5',
        dueDate: new Date('2026-01-20'),
        estimatedHours: 6,
        labels: ['frontend', 'backend'],
        checklist: [
            { id: 'ch25', text: 'Form UI', completed: true },
            { id: 'ch26', text: 'Validation', completed: false },
        ],
        createdAt: new Date('2026-01-12'),
        updatedAt: new Date('2026-01-15'),
    },
]

// Mock Invoices
export const mockInvoices: Invoice[] = [
    {
        id: 'inv1',
        invoiceNumber: 'INV-2024-001',
        clientId: 'c1',
        projectId: 'p1',
        type: 'milestone',
        status: 'paid',
        lineItems: [
            { id: 'li1', name: 'Website Design', quantity: 1, rate: 75000, taxPercentage: 18 },
        ],
        subtotal: 75000,
        tax: 13500,
        total: 88500,
        number: 'INV-2024-001',
        date: new Date('2024-02-28'),
        dueDate: new Date('2024-03-15'),
        paidDate: new Date('2024-03-10'),
        createdAt: new Date('2024-02-28'),
        updatedAt: new Date('2024-03-10'),
    },
    {
        id: 'inv2',
        invoiceNumber: 'INV-2024-002',
        clientId: 'c2',
        projectId: 'p2',
        type: 'advance',
        status: 'paid',
        lineItems: [
            { id: 'li2', name: 'E-commerce Development - Advance', quantity: 1, rate: 300000, taxPercentage: 18 },
        ],
        subtotal: 300000,
        tax: 54000,
        total: 354000,
        number: 'INV-2024-002',
        date: new Date('2024-04-01'),
        dueDate: new Date('2024-04-15'),
        paidDate: new Date('2024-04-10'),
        createdAt: new Date('2024-04-01'),
        updatedAt: new Date('2024-04-10'),
    },
    {
        id: 'inv3',
        invoiceNumber: 'INV-2026-001',
        clientId: 'c2',
        projectId: 'p2',
        type: 'milestone',
        status: 'pending',
        lineItems: [
            { id: 'li3', name: 'Phase 3 - Launch & Deployment', quantity: 1, rate: 200000, taxPercentage: 18 },
        ],
        subtotal: 200000,
        tax: 36000,
        total: 236000,
        number: 'INV-2026-001',
        date: new Date('2026-01-15'),
        dueDate: new Date('2026-02-15'),
        createdAt: new Date('2026-01-15'),
        updatedAt: new Date('2026-01-15'),
    },
    {
        id: 'inv4',
        invoiceNumber: 'INV-2026-002',
        clientId: 'c3',
        projectId: 'p3',
        type: 'amc',
        status: 'overdue',
        lineItems: [
            { id: 'li4', name: 'Monthly Retainer - January 2026', quantity: 1, rate: 100000, taxPercentage: 18 },
        ],
        subtotal: 100000,
        tax: 18000,
        total: 118000,
        number: 'INV-2026-002',
        date: new Date('2025-12-28'),
        dueDate: new Date('2026-01-05'),
        createdAt: new Date('2025-12-28'),
        updatedAt: new Date('2026-01-10'),
    },
    {
        id: 'inv5',
        invoiceNumber: 'INV-2026-003',
        clientId: 'c5',
        projectId: 'p5',
        type: 'milestone',
        status: 'paid',
        lineItems: [
            { id: 'li5', name: 'Design & Prototype', quantity: 1, rate: 96000, taxPercentage: 18 },
        ],
        subtotal: 96000,
        tax: 17280,
        total: 113280,
        number: 'INV-2026-003',
        date: new Date('2024-10-15'),
        dueDate: new Date('2024-10-31'),
        paidDate: new Date('2024-10-28'),
        createdAt: new Date('2024-10-15'),
        updatedAt: new Date('2024-10-28'),
    },
]

// Mock Time Entries
export const mockTimeEntries: TimeEntry[] = [
    {
        id: 'te1',
        projectId: 'p2',
        taskId: 't2',
        userId: 'u4',
        startTime: new Date('2026-01-15T09:00:00'),
        endTime: new Date('2026-01-15T12:30:00'),
        duration: 210,
        note: 'Implemented cart state management',
        createdAt: new Date('2026-01-15'),
    },
    {
        id: 'te2',
        projectId: 'p2',
        taskId: 't2',
        userId: 'u4',
        startTime: new Date('2026-01-15T14:00:00'),
        endTime: new Date('2026-01-15T17:00:00'),
        duration: 180,
        note: 'Add/remove cart items functionality',
        createdAt: new Date('2026-01-15'),
    },
    {
        id: 'te3',
        projectId: 'p3',
        taskId: 't6',
        userId: 'u5',
        startTime: new Date('2026-01-15T10:00:00'),
        endTime: new Date('2026-01-15T13:00:00'),
        duration: 180,
        note: 'Built basic video player',
        createdAt: new Date('2026-01-15'),
    },
    {
        id: 'te4',
        projectId: 'p5',
        taskId: 't10',
        userId: 'u5',
        startTime: new Date('2026-01-14T09:30:00'),
        endTime: new Date('2026-01-14T12:00:00'),
        duration: 150,
        note: 'Created filter UI components',
        createdAt: new Date('2026-01-14'),
    },
    {
        id: 'te5',
        projectId: 'p7',
        taskId: 't14',
        userId: 'u5',
        startTime: new Date('2026-01-15T15:00:00'),
        endTime: new Date('2026-01-15T18:00:00'),
        duration: 180,
        note: 'Form validation logic',
        createdAt: new Date('2026-01-15'),
    },
]

// Mock Communication Logs
export const mockCommunicationLogs: CommunicationLog[] = [
    {
        id: 'cl1',
        clientId: 'c2',
        type: 'call',
        summary: 'Discussed payment gateway requirements',
        nextFollowUp: new Date('2026-01-20'),
        createdBy: 'u2',
        createdAt: new Date('2026-01-15'),
    },
    {
        id: 'cl2',
        clientId: 'c3',
        type: 'whatsapp',
        summary: 'Shared progress update for quiz module',
        createdBy: 'u2',
        createdAt: new Date('2026-01-14'),
    },
    {
        id: 'cl3',
        clientId: 'c5',
        type: 'email',
        summary: 'Sent design mockups for approval',
        nextFollowUp: new Date('2026-01-18'),
        createdBy: 'u2',
        createdAt: new Date('2026-01-13'),
    },
]

// Mock Files
export const mockFiles: FileItem[] = [
    {
        id: 'f1',
        name: 'design-mockup-v1.fig',
        type: 'figma',
        size: 2048000,
        url: '/files/design-mockup-v1.fig',
        projectId: 'p2',
        uploadedBy: 'u3',
        uploadedAt: new Date('2026-01-10'),
    },
    {
        id: 'f2',
        name: 'requirements.pdf',
        type: 'pdf',
        size: 512000,
        url: '/files/requirements.pdf',
        projectId: 'p2',
        clientId: 'c2',
        uploadedBy: 'u2',
        uploadedAt: new Date('2026-01-08'),
    },
    {
        id: 'f3',
        name: 'logo-final.svg',
        type: 'svg',
        size: 45000,
        url: '/files/logo-final.svg',
        clientId: 'c2',
        uploadedBy: 'u3',
        uploadedAt: new Date('2026-01-12'),
    },
]

// Mock Activities
export const mockActivities: Activity[] = [
    {
        id: 'a1',
        type: 'task_created',
        userId: 'u2',
        projectId: 'p2',
        taskId: 't4',
        description: 'Created task "Order management dashboard"',
        createdAt: new Date('2026-01-12T10:30:00'),
    },
    {
        id: 'a2',
        type: 'status_changed',
        userId: 'u4',
        projectId: 'p2',
        taskId: 't2',
        description: 'Changed status from "todo" to "in-progress"',
        metadata: { from: 'todo', to: 'in-progress' },
        createdAt: new Date('2026-01-15T09:00:00'),
    },
    {
        id: 'a3',
        type: 'timer_started',
        userId: 'u4',
        projectId: 'p2',
        taskId: 't2',
        description: 'Started timer on "Implement shopping cart"',
        createdAt: new Date('2026-01-15T09:05:00'),
    },
    {
        id: 'a4',
        type: 'invoice_created',
        userId: 'u2',
        projectId: 'p2',
        description: 'Created invoice INV-2026-001',
        metadata: { invoiceId: 'inv3', amount: 236000 },
        createdAt: new Date('2026-01-15T11:00:00'),
    },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
    {
        id: 'n1',
        title: 'Task Due Soon',
        message: 'Task "Payment gateway integration" is due in 2 days',
        read: false,
        link: '/tasks/t3',
        createdAt: new Date('2026-01-15T08:00:00'),
    },
    {
        id: 'n2',
        title: 'Invoice Overdue',
        message: 'Invoice INV-2026-002 is overdue',
        read: false,
        link: '/invoices/inv4',
        createdAt: new Date('2026-01-15T09:00:00'),
    },
    {
        id: 'n3',
        title: 'New Comment',
        message: 'Priya Singh commented on "Shopping cart"',
        read: true,
        link: '/tasks/t2',
        createdAt: new Date('2026-01-14T16:30:00'),
    },
    {
        id: 'n4',
        title: 'Client Approval Needed',
        message: 'Task "Product search & filters" needs client approval',
        read: false,
        link: '/tasks/t5',
        createdAt: new Date('2026-01-14T14:00:00'),
    },
]

