const mongoose = require('mongoose');

const settingSchema = new mongoose.Schema({
    type: { type: String, default: 'general', unique: true },
    companyProfile: {
        name: { type: String, default: 'Nexprism Agency' },
        logo: String,
        icon: String,
        themeColor: { type: String, default: '#0f172a' }, // Default slate-900
        logoWidth: { type: String, default: 'auto' },
        logoHeight: { type: String, default: '32px' },
        website: String,
        address: String,
        phone: String,
        email: String,
        gst: String,
        pan: String,
        currency: { type: String, default: 'INR' },
        timezone: { type: String, default: 'Asia/Kolkata' },
        businessHours: String,
        subtitle: { type: String, default: 'Professional Services' }
    },
    billing: {
        razorpayKey: String,
        razorpaySecret: String,
        cashfreeClientId: String,
        cashfreeClientSecret: String,
        cashfreeMode: { type: String, enum: ['sandbox', 'production'], default: 'sandbox' },
        invoiceFormat: { type: String, default: 'INV-2026-001' },
        taxRate: { type: Number, default: 18 },
        paymentTerms: { type: String, default: '15' },
        termsAndConditions: { type: String, default: 'Thank you for your business. Payment is expected within due date. Late payments may incur fees.' },
        bankDetails: { type: String, default: '' },
        invoiceLogo: { type: String },
        invoicePhone: { type: String, default: '+91 7505974545' },
        invoiceEmail: { type: String, default: 'Info@nexprism.com' },
        invoiceWebsite: { type: String, default: 'nexprism.com' },
        invoiceFooterHeading: { type: String, default: 'THANK YOU FOR YOUR BUSINESS' },
        lateFee: Number
    },
    notifications: {
        emailAlerts: { type: Boolean, default: true },
        projectUpdates: { type: Boolean, default: true },
        taskAssignments: { type: Boolean, default: true },
        taskOverdue: { type: Boolean, default: true },
        invoiceDue: { type: Boolean, default: true },
        clientApproval: { type: Boolean, default: true },
        projectDeadline: { type: Boolean, default: true }
    },
    automations: {
        autoSendOverdueReminders: { type: Boolean, default: true },
        autoGenerateDomainQuotes: { type: Boolean, default: true },
    },
    emailSettings: {
        host: String,
        port: { type: Number, default: 587 },
        user: String,
        pass: String,
        fromEmail: String,
        fromName: String,
        secure: { type: Boolean, default: false }
    },
    roles: [{
        name: { type: String, required: true }, // e.g. 'admin'
        label: { type: String }, // e.g. 'Administrator'
        permissions: { type: Object, default: {} }
    }],
    dashboardLayouts: {
        type: mongoose.Schema.Types.Mixed,
        default: {}
    },
    payroll: {
        offDays: { type: [Number], default: [0] }, // 0 for Sunday
        holidays: [{
            date: { type: String }, // YYYY-MM-DD
            label: { type: String }
        }]
    },
    attendance: {
        standardShiftHours: { type: Number, default: 9.0 },
        lunchBreakHours: { type: Number, default: 1.0 },
        halfDayThresholdHours: { type: Number, default: 4.5 },
        gracePeriodMinutes: { type: Number, default: 15 },
        shiftStartTime: { type: String, default: '09:30' },
        shiftEndTime: { type: String, default: '18:30' },
    },
    apiKeys: {
        gemini: { type: String, default: '' },
        openai: { type: String, default: '' },
    },
    whatsappSettings: {
        connectionMode: { type: String, enum: ['qr_code', 'cloud_api'], default: 'qr_code' },
        qrSessionStatus: { type: String, enum: ['disconnected', 'qr_ready', 'connected'], default: 'disconnected' },
        connectedPhone: { type: String, default: '' },
        connectedAt: Date,
        sessionToken: { type: String, default: '' },
        phoneNumberId: { type: String, default: '' },
        accessToken: { type: String, default: '' },
        businessAccountId: { type: String, default: '' },
        webhookVerifyToken: { type: String, default: 'nexcrm_wa_secret' },
        autoCreateLead: { type: Boolean, default: true },
        defaultStage: { type: String, default: 'new' },
        templateName: { type: String, default: 'invoice_notification' },
        enabled: { type: Boolean, default: true }
    },
    updatedAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Setting', settingSchema);
